# Generated by Django 3.1.5 on 2021-01-21 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=50)),
                ('job_date', models.TimeField(default=datetime.datetime(2021, 1, 21, 14, 27, 19, 45330, tzinfo=utc))),
                ('job_estimated_time', models.IntegerField()),
                ('job_actual_time', models.IntegerField(default=0)),
                ('job_desc', models.CharField(max_length=1000)),
                ('job_notes', models.CharField(max_length=500)),
                ('job_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TechExpert',
            fields=[
                ('expert_id', models.AutoField(primary_key=True, serialize=False)),
                ('expert_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=30)),
                ('task_desc', models.CharField(max_length=1000)),
                ('task_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.job')),
                ('task_tech_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.techexpert')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.status'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_tech_expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.techexpert'),
        ),
    ]
