# Generated by Django 3.1.5 on 2021-01-21 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.TimeField(default=datetime.datetime(2021, 1, 21, 14, 30, 41, 745718, tzinfo=utc)),
        ),
    ]
