# Generated by Django 3.1.5 on 2021-01-21 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210121_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.TimeField(default=datetime.datetime(2021, 1, 21, 15, 4, 15, 474970, tzinfo=utc)),
        ),
    ]
