# Generated by Django 3.1.5 on 2021-01-21 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210121_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.TimeField(default=datetime.datetime(2021, 1, 21, 15, 34, 56, 785909, tzinfo=utc)),
        ),
    ]
