# Generated by Django 3.1.5 on 2021-01-21 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210121_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_created_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 21, 18, 59, 57, 706294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.TimeField(default=datetime.datetime(2021, 1, 21, 18, 59, 57, 705761, tzinfo=utc)),
        ),
    ]
