# Generated by Django 3.1.5 on 2021-01-22 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210121_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_title',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.TimeField(default=datetime.datetime(2021, 1, 22, 9, 44, 4, 114514, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_created_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 22, 9, 44, 4, 115023, tzinfo=utc)),
        ),
    ]
