# Generated by Django 3.1.5 on 2021-01-22 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210122_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 22, 17, 32, 7, 975282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_created_date',
            field=models.DateField(default=datetime.datetime(2021, 1, 22, 17, 32, 7, 975847, tzinfo=utc)),
        ),
    ]
